### ISSUE TITLE
DeleteEntity method

### ISSUE THREAD

**Issue by ndureiss** [7PH/deadlock.js-lightorm#1]
What do you think about adding DeleteEntity method into [MySQL](https://github.com/7PH/deadlock.js-lightorm/blob/master/src/entity/database/MySQL.ts) ?

This method can take care of delete statement handling exceptions and so on...

**Comment by 7PH** [comment]
I think that this should be possible (and useful)
Will be looking into the best way to implement it

**Comment by ndureiss** [comment]
By exception I thought to SQL Exception happening when you try to delete an entry which is referenced in an other table etc :monkey_face:

**Comment by 7PH** [comment]
Fixed by #2, published as deadlockjs-lightorm@0.5.0

You can use
`MySQL.deleteEntity(mysql: Connection, instance: Entity)`

to delete an entity. The entity must have a primary key. If there is none, an exception will be thrown.
