### ISSUE TITLE
UpdateEntity method

### ISSUE THREAD

**Issue by ndureiss** [7PH/deadlock.js-lightorm#3]
What do you think about adding UpdateEntity method into [MySQL](https://github.com/7PH/deadlock.js-lightorm/blob/master/src/entity/database/MySQL.ts) ? :smile: 

This method can take care of update statement for **one or more** fields of an entity, handling exceptions and so on... It could be a good complement to [insert](https://github.com/7PH/deadlock.js-lightorm/blob/073435a3a92e9c1f2295e48e89989cf707120b97/src/entity/database/MySQL.ts#L159) and [delete](https://github.com/7PH/deadlock.js-lightorm/blob/073435a3a92e9c1f2295e48e89989cf707120b97/src/entity/database/MySQL.ts#L207) methods.

**Comment by 7PH** [comment]
I've just published `0.5.1` which adds an `syncEntity<Class>(mysql: Connection, instance: Class): Promise<void>` method to the MySQL helper. It will try to update all the given instance fields.

**Comment by ndureiss** [comment]
Perfect! Many thanks!
